# 🧪 Название workflow — так он будет отображаться во вкладке Actions
name: Main Taski workflow

# 📅 Указываем, когда запускать workflow:
# В данном случае — при каждом push в ветку main
on:
  push:
    branches:
      - main

jobs:
  # Название джоба — здесь 'tests', но может быть любым
  tests:
    # GitHub Actions будет выполнять джоб на виртуальной машине Ubuntu
    runs-on: ubuntu-latest

    # 🐘 Блок services — аналог docker-compose:
    # описываем дополнительные контейнеры, которые будут запущены
    # вместе с раннером. В нашем случае — PostgreSQL.
    services:
      postgres:
        # 🐳 Официальный образ PostgreSQL, версия 13.10
        image: postgres:13.10
        # Переменные окружения, необходимые для запуска контейнера с БД
        # Эти данные будут использованы только во время тестов
        env:
          POSTGRES_USER: django_user           # имя пользователя БД
          POSTGRES_PASSWORD: django_password   # пароль
          POSTGRES_DB: django_db               # имя тестовой БД
        # Пробрасываем порт с контейнера на хост:
        # 5432 хоста → 5432 контейнера (стандартный порт PostgreSQL)
        ports:
          - 5432:5432
        # ⏳ Проверка готовности сервиса.
        # Без этой проверки тесты могут запуститься раньше,
        # чем сервер БД будет готов принимать подключения.
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      # 1️⃣ Загружаем код репозитория в рабочую директорию раннера
      - name: Check out code
        uses: actions/checkout@v3

      # 2️⃣ Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12    # версия Python для прогона линтера и тестов

      # 3️⃣ Устанавливаем зависимости проекта и линтеров
      - name: Install dependencies
        run: |
          # Обновляем pip и инструменты сборки
          python -m pip install --upgrade pip setuptools
          # Устанавливаем flake8 и flake8-isort для проверки стиля кода
          pip install flake8==6.0.0 flake8-isort==6.0.0
          # Устанавливаем зависимости из requirements.txt для Django проекта
          pip install -r ./backend/requirements.txt 

      # 4️⃣ Запускаем линтер flake8 и тесты
      - name: Test with flake8 and django tests
        # Передаём Django параметры для подключения к БД
        # (они должны совпадать с настройками в settings.py)
        env:
          POSTGRES_USER: django_user           # имя пользователя БД
          POSTGRES_PASSWORD: django_password   # пароль пользователя БД
          POSTGRES_DB: django_db               # имя БД
          DB_HOST: 127.0.0.1                   # хост — это локальный адрес раннера
          DB_PORT: 5432                        # порт, проброшенный в services
        run: |
          # Запускаем линтер flake8 для папки backend
          python -m flake8 backend/
          # Переходим в директорию проекта Django
          cd backend/
          # Запускаем встроенные Django тесты
          python manage.py test
